### ISSUE TITLE
Shift Old Code to a different branch. 

### ISSUE THREAD

**Issue by srbhr** [Git-Commit-Show/100-Days-of-Code#234]
Every time someone clones this repo, they will have that old code as well. Planning to shift this to another branch.

**Comment by adityajoshi-08** [comment]
Yes, we should be doing that, this will make the repo look much more cleaner as well.

**Comment by srbhr** [comment]
Yes @adityajoshi-08 updated by removing the old code itself. There's another branch, iteration-1 that contains the old code. I guess that would do. : )
