### ISSUE TITLE
[IDEA] Add a license

### ISSUE THREAD

**Issue by Panquesito7** [Git-Commit-Show/100-Days-of-Code#52]
**Description**

We should add a license to this repository. This way, people will know what and what not they can do with this repository, permissions, notices, etc.. I suggest adding the [**MIT license**](https://mit-license.org).

**Additional Context**    

https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/

**Comment by srbhr** [comment]
@Panquesito7 
## DONE
Added MIT License

Thanks!

**Comment by Panquesito7** [comment]
Amazing, thanks! 😄
