### ISSUE TITLE
[Enhancement] Shift the maintainers part to the bottom and the "Thanks to contributors" to above FAQs

### ISSUE THREAD

**Issue by srbhr** [Git-Commit-Show/100-Days-of-Code#69]
@Panquesito7 can you shift the Thanks Message to above FAQs, as a community we'd like to thank our contributors first. As they are the core of this 100 Days of Code. 

Thanks, 
Saurabh

**Comment by Panquesito7** [comment]
Sure! Do you want to work on this or should I do it?

**Comment by srbhr** [comment]
Yeah @Panquesito7  you should work upon it! You know better! 😁
